### ISSUE TITLE
Ability to test individual modules

### ISSUE THREAD

**Issue by kitsonk** [dojo/cli-test-intern#22]
**Discussion** 

Would we have the ability to test individual modules via the test command in a user friendly way?  For example, should we support something like: `dojo test -m unit/FooBar` to only run the specified tests instead of the entire unit or functional suite?

**Comment by rishson** [comment]
Maybe a more lofty goal would be to re-run all tests that touch code changed (under a watch).
ITMT, I think the ability to run a single test would be 👍

**Comment by dylans** [comment]
> Maybe a more lofty goal would be to re-run all tests that touch code changed (under a watch).
ITMT, I think the ability to run a single test would be 👍

It's a good idea, though I think the individual test modules is quite a bit easier to support with Intern out of the box (since you can easily tell Intern to run a particular suite). I guess with a watch command you could construct a list of modules that you could pass into Intern's grep parameter.

**Comment by dylans** [comment]
Note that if we do get a watch command working for rerunning tests, that would be highly useful for Intern 4 as well.

**Comment by kitsonk** [comment]
The biggest challenge I see to that feature is figuring the dependency tree of dependent/effected modules.  I assume it would be some sort of custom plugin for webpack?

**Comment by rishson** [comment]
Initially, I think we can do this 'by convention', in that the watcher tells us which files have changed, so we can re-run the corresponding tests, e.g.

if `src/somePath/myFile.ts` changes, then re-run `tests/unit/somPath/myFile.ts`

**Comment by rishson** [comment]
We can get become cleverererer as time goes on, e.g. detect changes at a finer granularity than file-level, allow for re-running files that don't meet the directory structure convention..

**Comment by edhager** [comment]
If you have a large number of tests and one is failing, Intern allows you to run only that suite.  Intern 4's "grep" option allows you to narrow it down to just the test case.  This is extremely helpful in speeding up develop of a fix for the failing test.  Once the fix is in place, then you run all of the tests.

**Comment by agubler** [comment]
This is supported using the `filter` options that is transformed into a `grep` under the hood.

https://github.com/dojo/cli-test-intern/blob/master/src/runTests.ts#L55
