### ISSUE TITLE
Test in browser option

### ISSUE THREAD

**Issue by tomdye** [dojo/cli-test-intern#24]
**Enhancement** 

It would be useful to have a `browser` flag for using the browser test runner for straight forward debugging etc..
Command could simply print a link to the console which the user to click to open the runner in their browser of choice.

**Comment by kitsonk** [comment]
Is this really critical for `beta2` @dylans?

@tomdye do you mean running unit tests in the browser?  I would expect that to equate to what is typically "proxyOnly" intern configuration.  That would be the only way to guarantee that the tests were serveable.

I think we need to think about exactly what configuration aligns to what... because they are a bit confusing with common use cases.  We already have a flag of `--browser`.  I would see this as another version of the configuration flag we have, though as discussion in other threads indicates that that is rather confusing as well.

**Comment by agubler** [comment]
A url to run tests in a browser is printed when tests have finished.
